name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Test"
          replace: "Mest"
          include: "index.html"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/unique-sso/unique-sso/sandbox.blue-portal.site
          target: production
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UNIQUE_SSO_PROD }}'
          channelId: live
          projectId: unique-sso-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/unique-sso/unique-sso/sandbox.blue-portal.site
          target: staging
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UNIQUE_SSO_STAGING }}'
          channelId: live
          projectId: unique-sso-staging
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
